### ISSUE TITLE
Build problem: illegal option for e3.bash

### ISSUE THREAD

**Issue by ttkorhonen** [icshwi/e3#16]
I cloned a fresh e3 version from the repo. I start to follow the instructions in the README.
I get the following error:

$make env
e3.bash: illegal option -- g
Usage    : e3.bash [ -ctifeal ] <option> 
...<lots of text>...

am I doing something wrong? I am pretty sure that this used to work...

**Comment by jeonghanlee** [comment]
#ttkorhonen  you did the correct, I did update to match new options requested by Javi in the Makefile.  Please use the direct shell commands instead of Makefile.

**Comment by jeonghanlee** [comment]
Resolved by updating README
