### ISSUE TITLE
e3.bash should handle root privilege according to the e3 installation location 

### ISSUE THREAD

**Issue by jeonghanlee** [icshwi/e3#23]
The e3 building system can detect whether it needs root privilege or not according to `EPICS_BASE`. However, `e3.bash` cannot detect it automatically.  Most case, we don't have any issue. However, if one compiles a module with root privilege, `clean_module` cannot remove that directory without `sudo`. So, it is quite possible to check `EPICS_BASE` within `e3.bash`. 

I will leave this issue here in order to clean up them later.

**Comment by greyltc** [comment]
If it were my project, I'd disallow compiling as the root user

**Comment by jeonghanlee** [comment]
implemented at  fa2bbff
