### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by greyltc** [icshwi/e3#24]
All but one of the Arch packages I need can be installed like this:
```
pacman -Syu  tcl glibmm libtirpc readline libxt libxmu libxpm pcre net-snmp re2c darcs python2 netcdf hdf5 libpng bzip2 libxml2 libxml2 libusb libusb-compat remake systemd linux-headers mercurial boost boost-libs libraw1394 opencv
```
the tclx package is also needed but it's the only one that's not in an official Arch repository. Line number 3 of `e3/e3-require/require-ess/App/tools/expandDBD.tcl` is `package require Tclx`Do we really need it?

glibc beyond version 2.26 has removed some headers that asyn needs to compile. Arch is on version 2.28. The asyn build needs `-I/usr/include/tirpc` to find the new location for these header files (rpc.h and netconfig.h).

**Comment by jeonghanlee** [comment]
* yes, Tclx is the mandatory package.  Sorry about this. 
* e3-asyn has the option to enable this for powerpc so far, and we knew it already. I quickly added their support in linux86_x64 within configuration file.  You may try it let me know.  Set YES in the following file in e3/e3-asyn/configure

https://github.com/icshwi/e3-asyn/blob/master/configure/CONFIG_OPTIONS#L8

```
e3-asyn $ make init
e3-asyn $ make build
e3-asyn $ make install
```
Arch is the very interesting distribution, which I would like to try. :+1:

**Comment by jeonghanlee** [comment]
@greyltc , I updated e3-base and e3-require rules not to use the parallel building option. Whatever an environment use `-jN` option, now the e3 building system will ignore them. I will check them with travis.

**Comment by greyltc** [comment]
Great! I've almost got the Arch package done now. I'll update & close this issue with instructions on how to install it when I'm finished.

**Comment by jeonghanlee** [comment]
@greyltc can you check your linkedin msg, invitation?

**Comment by jeonghanlee** [comment]
@greyltc  how about your Arch packaging for e3?  And if you are OK, can I say that e3 support Arch Linux? If you have time, can I ask you a short README.Arch for installation on Arch?

**Comment by jeonghanlee** [comment]
I've found the e3 package on archlinux. So I think, this issue was resolved. 
https://aur.archlinux.org/packages/ess-epics/

If one needs more issues, please re-open it again.
