### ISSUE TITLE
e3.bash "die"  command

### ISSUE THREAD

**Issue by rizzoa** [icshwi/e3#25]
Hi Han,
I noticed that in the e3.bash there are several lines with "... || die 1 " commands.
This looks to me to some leftover from some perl script.
Could you please check?

**Comment by jeonghanlee** [comment]
The `die` is the function defined in https://github.com/icshwi/e3/blob/master/.cfgs/.e3_functions.cfg#L32
If you have the better idea, you can propose :)

**Comment by rizzoa** [comment]
Hi Han,
ok, I guess that there is no need to make something better than this function,
anyway you should fix the e3_function.cfg line 768 and line 958.
There is a typo, you should remove the double quote in the ${sudo_cmd}, otherwise you get some command not find error.

**Comment by jeonghanlee** [comment]
Thank you for your help!
